apiVersion: apps/v1
kind: Deployment
metadata:
  name: izdelki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izdelki
  template:
    metadata:
      labels:
        app: izdelki
    spec:
      containers:
        - image: rsoskupina50/izdelki:lastest
          name: izdelki
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/mzcgdhno
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: mzcgdhno
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: HNLXcZhB65htYCWwE5NALiLLS420Nn3T
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: izdelki
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: izdelki
