INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (2, 'Alpsko mleko', 'Hofer', 10, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (1, 'Alpsko mleko', 'Merkator', 9, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (3, 'Alpsko mleko', 'Spar', 7, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (3, 'Čokolada Milka', 'Hofer', 5, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (3, 'Čokolada Milka', 'Merkator',6, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (2, 'Čokolada Milka', 'Spar', 9, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (15, 'Fructal Pelinkovec', 'Hofer', 10, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (11, 'Fructal Pelinkovec', 'Merkator', 10, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (12, 'Fructal Pelinkovec', 'Spar', 10, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (5, 'Sladoled Planica', 'Hofer', 6, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (6, 'Sladoled Planica', 'Merkator', 8, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (4, 'Sladoled Planica', 'Spar', 5, 'Sladice');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (1, 'Pepsi', 'Hofer', 7, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (2, 'Pepsi', 'Merkator', 8, 'Pijača');
INSERT INTO izdelki_metadata (cena, naziv, trgovina, ocena, tip) VALUES (1, 'Pepsi', 'Spar', 7, 'Pijača');